/**
 * Report generator — creates concise, actionable reports.
 */
import { getTrendingRepos, getAIAgentTrending, getRecentReleases, searchRepos } from "./github.js";
import { multiSearch } from "./search-sources.js";

function formatStars(n) {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Generate the daily trending report.
 */
export function generateDailyReport() {
  const trending = getTrendingRepos({ days: 7, limit: 10 });
  const aiAgents = getAIAgentTrending({ days: 7, limit: 10 });
  const releases = getRecentReleases({ days: 7 });

  let report = `# Trend Scout Daily Report — ${today()}\n\n`;

  // Section 1: Hottest new repos
  report += `## Hot New Repos This Week\n\n`;
  report += `| # | Repo | Stars | Lang | Description |\n`;
  report += `|---|------|-------|------|-------------|\n`;
  trending.forEach((r, i) => {
    const desc = (r.description || "—").slice(0, 80);
    report += `| ${i + 1} | [${r.full_name}](${r.html_url}) | ${formatStars(r.stargazers_count)} | ${r.language || "—"} | ${desc} |\n`;
  });

  // Section 2: AI & Agent innovations
  report += `\n## AI Agent & MCP Innovations\n\n`;
  if (aiAgents.length === 0) {
    report += `_No notable new AI agent repos this week._\n`;
  } else {
    report += `| # | Repo | Stars | Topics | Description |\n`;
    report += `|---|------|-------|--------|-------------|\n`;
    aiAgents.forEach((r, i) => {
      const desc = (r.description || "—").slice(0, 70);
      const topics = (r.topics || r.topic || []).slice(0, 3).join(", ");
      report += `| ${i + 1} | [${r.full_name}](${r.html_url}) | ${formatStars(r.stargazers_count)} | ${topics} | ${desc} |\n`;
    });
  }

  // Section 3: Notable releases
  report += `\n## Notable Releases\n\n`;
  if (releases.length === 0) {
    report += `_No major releases from watched repos this week._\n`;
  } else {
    releases.forEach((r) => {
      report += `- **${r.repo}** [${r.tag}](${r.url}) — ${r.name || r.tag} (${r.date.slice(0, 10)})\n`;
    });
  }

  // Footer
  report += `\n---\n_Generated by [Trend Scout](https://github.com/jerry/trend-scout) | ${new Date().toISOString()}_\n`;

  return report;
}

/**
 * Generate an on-demand search report (GitHub only).
 */
export function generateSearchReport(query) {
  const results = searchRepos(query, { limit: 10 });

  let report = `# Trend Scout Search: "${query}" — ${today()}\n\n`;
  report += `## GitHub Repos\n\n`;
  report += `| # | Repo | Stars | Lang | License | Updated | Description |\n`;
  report += `|---|------|-------|------|---------|---------|-------------|\n`;

  results.forEach((r, i) => {
    const desc = (r.description || "—").slice(0, 60);
    const license = r.license?.key || r.license?.spdxId || "—";
    const updated = (r.updatedAt || "—").slice(0, 10);
    report += `| ${i + 1} | [${r.fullName}](${r.url}) | ${formatStars(r.stargazersCount)} | ${r.language || "—"} | ${license} | ${updated} | ${desc} |\n`;
  });

  report += `\n---\n_Search powered by [Trend Scout](https://github.com/jerry/trend-scout) | ${new Date().toISOString()}_\n`;

  return report;
}

/**
 * Generate a deep multi-source search report (GitHub + Tavily + X + LinkedIn + YouTube).
 */
export async function generateDeepSearchReport(query, { sources = ["tavily", "x", "youtube", "hackernews"] } = {}) {
  // GitHub search (sync)
  const ghResults = searchRepos(query, { limit: 8 });

  // Multi-source search (async)
  const webResults = await multiSearch(query, { sources, maxPerSource: 4 });

  let report = `# Trend Scout Deep Search: "${query}" — ${today()}\n\n`;

  // GitHub section
  report += `## GitHub Repos\n\n`;
  report += `| # | Repo | Stars | Lang | Description |\n`;
  report += `|---|------|-------|------|-------------|\n`;
  ghResults.slice(0, 8).forEach((r, i) => {
    const desc = (r.description || "—").slice(0, 60);
    report += `| ${i + 1} | [${r.fullName}](${r.url}) | ${formatStars(r.stargazersCount)} | ${r.language || "—"} | ${desc} |\n`;
  });

  // Web/Tavily section
  for (const source of webResults) {
    const label = {
      tavily: "Web",
      x: "X / Twitter",
      linkedin: "LinkedIn",
      youtube: "YouTube",
      hackernews: "HackerNews / Tech Community",
    }[source.source] || source.source;

    report += `\n## ${label}\n\n`;

    if (source.answer) {
      report += `> ${source.answer.slice(0, 200)}\n\n`;
    }

    if (source.results?.length > 0) {
      source.results.forEach((r, i) => {
        const snippet = r.snippet ? ` — ${r.snippet.slice(0, 80)}` : "";
        report += `${i + 1}. [${r.title}](${r.url})${snippet}\n`;
      });
    } else {
      report += `_No results found._\n`;
    }
  }

  report += `\n---\n_Deep search powered by [Trend Scout](https://github.com/Angelov1314/trend-scout) | ${new Date().toISOString()}_\n`;

  return report;
}

/**
 * Generate enhanced daily report with AI buzz from social media.
 */
export async function generateEnhancedDailyReport() {
  // Base GitHub report (sync)
  let report = generateDailyReport();

  // Add social buzz section (async, via Tavily)
  if (!process.env.TAVILY_API_KEY) return report;

  const buzzResults = await multiSearch("AI agent breakthrough OR new MCP server OR Claude Code update", {
    sources: ["tavily", "x", "hackernews"],
    maxPerSource: 3,
  });

  // Insert before footer
  const footerIdx = report.lastIndexOf("\n---\n");
  let buzzSection = `\n## AI Buzz (Web & Social)\n\n`;

  for (const source of buzzResults) {
    if (source.results?.length === 0) continue;
    const label = { tavily: "Web", x: "X", hackernews: "HN" }[source.source] || source.source;
    for (const r of source.results || []) {
      buzzSection += `- **[${label}]** [${r.title}](${r.url})\n`;
    }
  }

  if (buzzSection.includes("[")) {
    report = report.slice(0, footerIdx) + buzzSection + report.slice(footerIdx);
  }

  return report;
}
